# Generated by Django 4.2 on 2024-05-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_accounts_gender_alter_accounts_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="address",
            field=models.CharField(max_length=250),
        ),
    ]