# Generated by Django 4.2 on 2024-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_accounts_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="profile_picture",
            field=models.ImageField(
                default=1, upload_to="accounts/profile_picture/%Y/%m/%d"
            ),
            preserve_default=False,
        ),
    ]
