# Generated by Django 4.2 on 2024-05-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_accounts_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="profile_picture",
            field=models.ImageField(
                blank=True, upload_to="accounts/profile_picture/%Y/%m/%d"
            ),
        ),
    ]