# Generated by Django 4.2 on 2024-05-31 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        ("accounts", "0009_alter_accounts_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_si", models.CharField(max_length=10)),
                ("address_gu", models.CharField(max_length=10)),
                ("address_detail", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="accounts",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.storeaddress"
            ),
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "store")},
            },
        ),
    ]
