# Generated by Django 4.2 on 2024-05-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_storeaddress_alter_accounts_address_bookmark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounts",
            name="address",
        ),
        migrations.AddField(
            model_name="accounts",
            name="address_detail",
            field=models.CharField(default="default_value", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accounts",
            name="address_gu",
            field=models.CharField(default="default_value", max_length=30),
        ),
        migrations.AddField(
            model_name="accounts",
            name="address_si",
            field=models.CharField(default="default_value", max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="StoreAddress",
        ),
    ]
