# Generated by Django 4.2 on 2024-05-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(upload_to="reviews/image/%Y/%m/%d"),
        ),
    ]
