# Generated by Django 4.2 on 2024-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="image",
            field=models.ImageField(blank=True, upload_to="stores/image/%Y/%m/%d"),
        ),
    ]
